# Generated by Django 2.0.5 on 2018-06-26 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='belongs_to',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'belongs_to',
                'verbose_name_plural': 'belongs_to',
            },
        ),
        migrations.CreateModel(
            name='teaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'teaches',
                'verbose_name_plural': 'teaches',
            },
        ),
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name_plural': 'batch'},
        ),
        migrations.AlterModelOptions(
            name='chooses',
            options={'verbose_name_plural': 'chooses'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'student'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name_plural': 'subject'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': 'teacher'},
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='ffirst_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='id',
            new_name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='middle_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='middle_namequit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teaches',
            name='batch_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.batch'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='subject_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.subject'),
        ),
        migrations.AddField(
            model_name='teaches',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.teacher'),
        ),
        migrations.AddField(
            model_name='belongs_to',
            name='batch_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.batch'),
        ),
        migrations.AddField(
            model_name='belongs_to',
            name='roll_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.student'),
        ),
    ]
