# Generated by Django 2.0.5 on 2018-06-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20180626_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='middle_namequit',
            new_name='middle_name',
        ),
    ]
