# Generated by Django 2.0.5 on 2018-07-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_auto_20180626_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
