# Generated by Django 2.0.5 on 2018-07-06 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0005_auto_20180704_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='belongs_to',
            name='batch_num',
            field=models.ForeignKey(db_column='batch_num', on_delete=django.db.models.deletion.CASCADE, to='schema.batch'),
        ),
        migrations.AlterField(
            model_name='belongs_to',
            name='roll_no',
            field=models.ForeignKey(db_column='roll_no', on_delete=django.db.models.deletion.CASCADE, to='schema.student'),
        ),
        migrations.AlterField(
            model_name='chooses',
            name='roll_no',
            field=models.ForeignKey(db_column='roll_no', on_delete=django.db.models.deletion.CASCADE, to='schema.student'),
        ),
        migrations.AlterField(
            model_name='chooses',
            name='subject_code',
            field=models.ForeignKey(db_column='subject_code', on_delete=django.db.models.deletion.CASCADE, to='schema.subject'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='batch_no',
            field=models.ForeignKey(db_column='batch_num', on_delete=django.db.models.deletion.CASCADE, to='schema.batch'),
        ),
        migrations.AlterField(
            model_name='teaches',
            name='teacher_id',
            field=models.ForeignKey(db_column='teacher_id', on_delete=django.db.models.deletion.CASCADE, to='schema.teacher'),
        ),
    ]
