# Generated by Django 2.0.5 on 2018-07-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0006_auto_20180706_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teaches',
            old_name='batch_no',
            new_name='batch_num',
        ),
    ]
