# Generated by Django 2.0.5 on 2018-07-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0008_auto_20180707_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='chooses',
            name='semester',
            field=models.CharField(default='2', max_length=1),
            preserve_default=False,
        ),
    ]
